#61 開発環境を切り替えるenvファイルを作成する
ISDL-dev/MERS pull request #68
Opened 2024-01-12 05:49 UTC by hoka-isdl

本番環境および開発環境でDBを切り替えるようにしました．
具体的には.env.prodと.env.devを環境設定ファイルで分割しています．
環境設定ファイルをdocker起動時に指定して実行することで本番環境か開発環境かを分けることができます．
/databaseディレクトリ直下にprod-dataかdev-dataを作成してデータをそれぞれ永続化するようにしています．

2024-01-27 06:21 UTC, Be3751 commented
対応ありがとう！テストはしてくれたんやっけ？
再現手順も記載してくれると助かる！俺の環境でもテストしてみたいので。

2024-01-27 07:17 UTC, hoka-isdl commented on README.md
> +docker-compose --env-file .env.prod up -d --build
テストは行っており，Databaseの切り替えが可能なことを確認いたしました．
こちらのコードを実行していただくと実装することができます．
ご確認よろしくお願いいたします．

2024-01-27 17:55 UTC, Be3751 commented on .env.dev
> +ENV="dev-"
```suggestion
ENV="dev"
```

2024-01-27 17:55 UTC, Be3751 commented on .env.prod
> +ENV="prod-"
```suggestion
ENV="prod"
```

2024-01-27 17:56 UTC, Be3751 commented on docker-compose.yml
> +        - ./database/${ENV}data:/var/lib/mysql
```suggestion
        - ./database/${ENV}-data:/var/lib/mysql
```

2024-01-27 18:16 UTC, Be3751 commented on .gitignore
> +/database/proddata
gitignoreされるようにハイフンを入れよう！
```suggestion
/database/dev-data
/database/prod-data
```

2024-01-27 18:45 UTC, Be3751 requested changes
一旦ざっとレビューしました！
対応よろしくお願いします。

2024-01-27 18:46 UTC, Be3751 commented on README.md
> +docker-compose --env-file .env.prod up -d --build
ありがとう！動作確認できました。

2024-01-29 04:45 UTC, hoka-isdl commented
上記の修正点に関しまして，全て修正完了いたしました．
再度ご確認よろしくお願いいたします．

2024-01-29 15:02 UTC, Be3751 approved these changes
LGTM

2024-01-31 09:12 UTC, merged